version: '3.9'

services:
  influxdb:
    image: influxdb:@latest
    env_file:
      - influx.env
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdb:/var/lib/influxdb:rw
    ports:
      - "8086:8086"
  telegraf:
    image: telegraf:@latest
    depends_on:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - influx.env

volumes:
  influxdb:
